'use strict'

export const popularCountries = [
  "UNITED STATES",
  "CHINA",
  "INDIA",
  "INDONESIA",
  "PAKISTAN",
  "BRAZIL",
  "NIGERIA",
  "BANGLADESH",
  "RUSSIA",
  "MEXICO",
  "JAPAN",
  "ETHIOPIA",
  "PHILIPPINES",
  "EGYPT",
  "VIETNAM",
  "DR CONGO",
  "TURKEY",
  "IRAN",
  "GERMANY",
  "THAILAND",
  "FRANCE",
  "UNITED KINGDOM",
  "ITALY",
  "SOUTH AFRICA",
  "TANZANIA",
  "MYANMAR",
  "SOUTH KOREA",
  "COLOMBIA",
  "KENYA",
  "SPAIN",
  "ARGENTINA",
  "ALGERIA",
  "SUDAN",
  "UKRAINE",
  "UGANDA",
  "IRAQ",
  "POLAND",
  "CANADA",
  "MOROCCO",
  "SAUDI ARABIA",
  "KAZAKHSTAN",
  "TURKMENISTAN",
  "SYRIA",
  "PALESTINE"
  ]; 
  

export const flags = [
  './IMG_flags/UNITEDSTATES.jpg.webp',
  './IMG_flags/CHINA.svg.png',
  './IMG_flags/INDIA.svg.png',
  './IMG_flags/INDONESIA.jpg.webp',
  './IMG_flags/PAKISTAN.jpg.webp',
  './IMG_flags/BRAZIL.svg.png',
  './IMG_flags/NIGERIA.svg.png',
  './IMG_flags/BANGLADESH.svg.png',
  './IMG_flags/RUSSIA.svg.png',
  './IMG_flags/MEXICO.svg.png',
  './IMG_flags/JAPAN.svg.png',
  './IMG_flags/ETHIOPIA.png',
  './IMG_flags/PHILIPPINES.jpg.webp',
  './IMG_flags/EGYPT.svg.png',
  './IMG_flags/VIETNAM.svg.png',
  './IMG_flags/DRCONGO.svg.png',
  './IMG_flags/TURKEY.svg.png',
  './IMG_flags/IRAN.webp',
  './IMG_flags/GERMANY.svg.png',
  './IMG_flags/THAILAND.svg.png',
  './IMG_flags/FRANCE.jpg.webp',
  './IMG_flags/UNITEDKINGDOM.svg.png',
  './IMG_flags/ITALY.svg.png',
  './IMG_flags/SOUTHAFRICA.svg.png',
  './IMG_flags/TANZANIA.jpg.webp',
  './IMG_flags/MYANMAR.svg.png',
  './IMG_flags/SOUTHKOREA.svg.png',
  './IMG_flags/COLOMBIA.svg.png',
  './IMG_flags/KENYA.svg.png',
  './IMG_flags/SPAIN.svg.png',
  './IMG_flags/ARGENTINA.jpg.webp',
  './IMG_flags/ALGERIA.svg.png',
  './IMG_flags/SUDAN.jpg.webp',
  './IMG_flags/UKRAINE.png.jpeg',
  './IMG_flags/UGANDA.jpg.webp',
  './IMG_flags/IRAQ.jpg.webp',
  './IMG_flags/POLAND.svg.png',
  './IMG_flags/CANADA.jpg',
  './IMG_flags/MOROCCO.svg.png',
  './IMG_flags/SAUDIARABIA.jpg.webp',
  './IMG_flags/KAZAKHSTAN.svg.png',
  './IMG_flags/TURKMENISTAN.svg.png',
  './IMG_flags/SYRIA.jpg',
  './IMG_flags/PALESTINE.svg.png'
]
